<?php
$collection = $block->getIngredientProducts();
if (!$collection->getSize()) {
    return;
}
?>

<div class="product-grid">
    <ol>
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items"><?php foreach ($collection as $product) : ?>
                    <li class="item product product-item">
                        <div class="product-item-info">
                            <a href="<?php echo $block->getProductUrl($product) ?>"
                               class="product photo product-item-photo">
                                <?php echo $block->getImage($product, 'related_products_list')->toHtml() ?></a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" title="<?php echo $block->escapeHtml($product->getName()) ?>"
                                       href="<?php echo $block->getProductUrl($product) ?>">
                                        <?php echo $block->escapeHtml($product->getName()) ?>
                                    </a>
                                </strong>
                                <?php echo $block->getProductPrice($product) ?>
                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()]);
                                $lineProductData = json_decode($postData); ?>
                                <form data-role="tocart-form" data-product-sku="<?= /* @NoEscape */ $product->getSku() ?>"
                                      action="<?= /* @NoEscape */ $lineProductData->action ?>" method="post">
                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $lineProductData->data->product ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?></ol>
        </div>
    </ol>
</div>

<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "bindSubmit": true
        }
    }
}
</script>